# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build-prod
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ashwinraj18/mte-ui:1.0
      - name: Docker Push
        run: docker push ashwinraj18/mte-ui:1.0
      - name: Deploy on AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_TWEAK_HOST }}
          username: ${{ secrets.AWS_TWEAK_USERNAME }}
          key: ${{ secrets.AWS_TWEAK_KEY }}
          port: 22
          script: |
            sudo docker rm -f mte-ui
            sudo docker rmi ashwinraj18/mte-ui:1.0
            sudo docker pull ashwinraj18/mte-ui:1.0
            sudo docker run -d -p 8090:8090 --name mte-ui ashwinraj18/mte-ui:1.0
            exit

